### ISSUE TITLE
Define and Document the doc writing process (internal TBD devs x dev rel)

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/docs-sitemap#9]
Stretch goal for Phase 2; could go in overall "CONTRIBUTING" section?

**Comment by bobbilee19** [comment]
This will not go into the contributing doc, the contributing doc is for OS external devs to learn how to work on our projects and how to get involved.

What we're talking about and solving in this Issue is...the docs process for internal devs to add something to the docs or a new project needs to go live, that whole process of collab between dev rel and OSE or just any ENG team on TBD...here is the hackmd draft for this flow so far, we're still working on it final rough draft isn't ready just yet today...https://hackmd.io/@mfCHHFWDRcaHJX3OqGUxLQ/r1dKQLUln/edit

**Comment by bobbilee19** [comment]
@kirahsapong I did not have as much time today to go over this doc again. Let's set up a time for thursday to go over it again. Async until then. I'm OOO tomorrow.

**Comment by ALRubinger** [comment]
@bobbilee19 wrote: 
> What we're talking about and solving in this Issue is...the docs process for internal devs to add something to the docs or a new project needs to go live, that whole process of collab between dev rel and OSE or just any ENG team on TBD

SGTM, so long as it's all public-facing! Eventually we'll have external contributor project leads and they can follow the same process, yeah?

**Comment by bobbilee19** [comment]
Yeah we can make this page for our devs to see and it can be in a repo after the discussion in HackMD. I'm not sure about it being in the docs-sitemap repo tho, let me think!

**Comment by bobbilee19** [comment]
Hey we have [two issues](https://github.com/TBD54566975/developer.tbd.website/issues/380) talking about the same thing, so I'm going to remove this one
